# Generated by Django 4.2.5 on 2023-11-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_adrress_address_product_slug'),
    ]

    operations = [
                migrations.RunSQL("""
            INSERT INTO store_collection (name)
            VALUES ('collection1')
        ""","""
            DELETE FROM store_collection
            WHERE name= 'collection1'
        """)
    ]
