# Generated by Django 5.0.1 on 2024-01-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_orderitem_product_alter_product_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='proudct',
            new_name='product',
        ),
    ]
